# Use the official PostgreSQL image
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=mockpitdb
ENV POSTGRES_USER=mockpituser
ENV POSTGRES_PASSWORD=mockpitpassword

# Expose port 5432 for PostgreSQL
EXPOSE 5432
